[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y software-properties-common",
  "add-apt-repository -y ppa:deadsnakes/ppa",
  "apt-get update",
  "apt-get install -y ffmpeg python3.10 python3.10-distutils python3.10-dev python3-pip",
  "update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1",
  "python3 -m pip install --upgrade pip setuptools wheel"
]

[phases.install]
cmds = [
  "npm config set registry https://registry.npmjs.org/",
  "npm config set strict-ssl false",
  "npm config set legacy-peer-deps true",
  "npm install --no-audit --no-fund --prefer-offline --legacy-peer-deps --force",
  "pip3 install torch torchaudio numpy --extra-index-url https://download.pytorch.org/whl/cpu",
  "pip3 install -r requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[mounts]
source = "/data"
destination = "/app/uploads"