[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y software-properties-common python3 python3-dev python3-pip libsndfile1 libopenblas-dev libsamplerate0 ffmpeg",
  "ln -sf /usr/bin/python3 /usr/bin/python",
  "python3 -m pip install --upgrade pip setuptools wheel",
  "echo 'Python installation:' && which python3 && python3 --version",
  "echo 'PATH environment:' && echo $PATH",
  "mkdir -p /root/.cache/torch/hub/snakers4_silero-vad_master"
]

[phases.install]
cmds = [
  "npm config set registry https://registry.npmjs.org/",
  "npm config set strict-ssl false",
  "npm config set legacy-peer-deps true",
  "npm install --no-audit --no-fund --prefer-offline --legacy-peer-deps --force",
  "pip3 install torch==2.0.1 torchaudio==2.0.2 numpy==1.24.3 --extra-index-url https://download.pytorch.org/whl/cpu",
  "pip3 install -r requirements.txt",
  "pip3 install librosa==0.10.1 soundfile==0.12.1 numba==0.58.1 scipy==1.11.4 resampy==0.4.2 requests==2.31.0",
  "python -c \"import torch; print('Torch version:', torch.__version__); print('Torch hub dir:', torch.hub.get_dir())\""
]

[phases.build]
cmds = [
  "npm run build"
]

[mounts]
source = "/data"
destination = "/app/uploads"