services:
  - type: web
    name: hassaniya-transcriber
    env: node
    buildCommand: apt-get update && apt-get install -y ffmpeg && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    packages:
      - ffmpeg 